timeout-coefficient: 20

threshold:
  efficacy: 70
  mutation-coverage: 70

mutants:
  arithmetic-base: true
  conditionals-boundary: true
  conditionals-negation: true
  increment-decrement: true
  invert-assignments: true
  invert-negation: true
