sonar.projectKey=dispatch
sonar.sources=.
sonar.host.url=http://10.27.27.202:9000
sonar.token=${env.SONAR_TOKEN}

sonar.go.coverage.reportPaths=coverage.out

# Optional: bessere Performance & saubere Ergebnisse
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/target/**,**/build/**
sonar.java.binaries=.
